#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
# bar settings
# # 打开状态栏
# yabai -m config status_bar                   on
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# 使用font-awesome替代罗马数字
# yabai -m config status_bar_space_icon_strip                      
# yabai -m config status_bar_power_icon_strip   
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon        

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# global settings

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  30             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               ctrl             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# 使用 font-awesome 替代罗马数字
#
yabai -m config status_bar_position bottom

yabai -m rule --add label=iTerm2 app="^iTerm2$" space=1 layer=normal
yabai -m rule --add label=chrome app="^Google Chrome$" space=2 layer=normal
yabai -m rule --add label=Joplin app="^Joplin$" space=4 layer=normal
yabai -m rule --add label=Xmind app="^Xmind$" space=4 layer=normal
yabai -m rule --add label=music app="^(网易云音乐|QQ音乐)$" space=5 layer=normal
# yabai -m rule --add label=music app="QQ音乐" space=6 layer=normal
yabai -m rule --add label=write app="Typora" space=2 layer=normal
devapp='^(Android Studio|PyCharm*|IntelliJ IDEA)$'
yabai -m rule --add label=dev app="${devapp}" space=3 layer=normal

otherApp='^(Finder|网易有道翻译|计算器|oss-browser|Sublime Text|TeamFile|阿里郎|访达|阿里钉|备忘录|梦幻模拟战|Calendar|日历|System Preferences|系统偏好设置|Mail)$'
yabai -m rule --add label=others app="${otherApp}" manage=off layer=normal

yabai -m rule --add app="^(Notification Cent.*|Alfred)$" layer=above


yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"


echo "yabai configuration loaded.."
